### ISSUE TITLE
NPE relating to rendering preview screens causes client crash

### ISSUE THREAD

**Issue by dextonanderson** [Ruinscraft/cinemadisplays-mod#10]
```---- Minecraft Crash Report ----
// Ooh. Shiny.

Time: 6/6/21 4:39 PM
Description: Unexpected error

java.lang.NullPointerException: Unexpected error
	at net.minecraft.class_1043.method_22793(class_1043.java:22)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:116)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:103)
	at net.minecraft.class_1041.method_15998(class_1041.java:308)
	at net.minecraft.class_310.method_1523(class_310.java:1068)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.minecraft.class_1043.method_22793(class_1043.java:22)
	at com.mojang.blaze3d.systems.RenderSystem.replayQueue(RenderSystem.java:116)
	at com.mojang.blaze3d.systems.RenderSystem.flipFrame(RenderSystem.java:103)

-- Affected level --
Details:
	All players: 1 total; [class_746['royalkingkb'/19, l='ClientLevel', x=34.62, y=66.00, z=-41.34]]
	Chunk stats: Client Chunk Cache: 1369, 490
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,65,0), Chunk: (at 0,4,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 17066 game time, 390000 day time
	Server brand: Paper
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:704)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226)
	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146)
	at net.fabricmc.loader.launch.knot.KnotClient.main(KnotClient.java:28)```

**Comment by dextonanderson** [comment]
I believe this should be fixed
